/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/shoes.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, -0.5]}>
        <group scale={0.2}>
          <mesh
            geometry={nodes.rtfkt_aj1_blinn4SG.geometry}
            material={materials.blinn4SG}
          />
          <mesh
            geometry={nodes.rtfkt_aj1_blinn5SG.geometry}
            material={materials.blinn5SG}
          />
          <mesh
            geometry={nodes.rtfkt_aj1_bladeblinn31SG.geometry}
            material={materials["blade:blinn31SG"]}
          />
          <mesh
            geometry={nodes.rtfkt_aj1_blinn3SG.geometry}
            material={materials.blinn3SG}
          />
          <mesh
            geometry={nodes.rtfkt_aj1_blinn6SG.geometry}
            material={materials.blinn6SG}
          />
          <mesh
            geometry={nodes.rtfkt_aj1_blinn7SG.geometry}
            material={materials.blinn7SG}
          />
          <mesh
            geometry={nodes.rtfkt_aj1_blinn2SG.geometry}
            material={materials.blinn2SG}
          />
          <mesh
            geometry={nodes.rtfkt_aj1_blinn1SG.geometry}
            material={materials.blinn1SG}
          />
          <mesh
            geometry={nodes.rtfkt_aj1_Material001.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.rtfkt_aj1_Material002.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/shoes.gltf");
